"""Initial schema

Revision ID: 4a667342d6d4
Revises: 
Create Date: 2025-11-03 11:06:58.744231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a667342d6d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('points_required', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recycling_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('waste_types_accepted', sa.JSON(), nullable=False),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recycling_points_latitude'), 'recycling_points', ['latitude'], unique=False)
    op.create_index(op.f('ix_recycling_points_longitude'), 'recycling_points', ['longitude'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('eco_score', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('carbon_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('activity', sa.String(length=255), nullable=False),
    sa.Column('carbon_amount_kg', sa.Float(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_logs_category'), 'carbon_logs', ['category'], unique=False)
    op.create_index(op.f('ix_carbon_logs_created_at'), 'carbon_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_carbon_logs_user_id'), 'carbon_logs', ['user_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_unit', sa.String(length=50), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('badge_reward', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_reward'], ['badges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_table('waste_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('waste_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('was_corrected', sa.Boolean(), nullable=True),
    sa.Column('carbon_saved_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_logs_created_at'), 'waste_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_waste_logs_user_id'), 'waste_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_logs_user_id'), table_name='waste_logs')
    op.drop_index(op.f('ix_waste_logs_created_at'), table_name='waste_logs')
    op.drop_table('waste_logs')
    op.drop_table('user_badges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_carbon_logs_user_id'), table_name='carbon_logs')
    op.drop_index(op.f('ix_carbon_logs_created_at'), table_name='carbon_logs')
    op.drop_index(op.f('ix_carbon_logs_category'), table_name='carbon_logs')
    op.drop_table('carbon_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recycling_points_longitude'), table_name='recycling_points')
    op.drop_index(op.f('ix_recycling_points_latitude'), table_name='recycling_points')
    op.drop_table('recycling_points')
    op.drop_table('badges')
    # ### end Alembic commands ###

