"""add_cfc_reports_table

Revision ID: abc123def456
Revises: 4a667342d6d4
Create Date: 2025-01-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc123def456'
down_revision: Union[str, None] = '4a667342d6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfc_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfc_reports_user_id'), 'cfc_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_cfc_reports_date'), 'cfc_reports', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cfc_reports_date'), table_name='cfc_reports')
    op.drop_index(op.f('ix_cfc_reports_user_id'), table_name='cfc_reports')
    op.drop_table('cfc_reports')
    # ### end Alembic commands ###

