import { motion } from "framer-motion";
import { useInView } from "framer-motion";
import { useRef } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, TrendingUp, BarChart3, Activity } from "lucide-react";

export default function ReportSubmissionSection() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  return (
    <section ref={ref} className="relative py-32 bg-gradient-to-b from-[#1a1a1a] via-[#0f0f0f] to-[#0a0a0a] overflow-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <h2 className="text-4xl sm:text-5xl md:text-6xl font-bold text-white mb-6 tracking-tight">
            Report your
            <br />
            <span className="bg-gradient-to-r from-emerald-400 to-teal-400 bg-clip-text text-transparent">
              carbon footprint
            </span>
          </h2>
          <p className="text-lg text-gray-300 max-w-2xl mx-auto">
            Understanding and tracking your carbon footprint is the first step towards creating a more sustainable future
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 50 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 50 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          <div className="glass-card rounded-2xl p-8 border border-white/10">
            <div className="space-y-6">
              <p className="text-gray-300 leading-relaxed text-lg mb-6">
                Your carbon footprint represents the total amount of greenhouse gases, including carbon dioxide and methane, 
                that are generated by your daily activities. By tracking your emissions across transportation, diet, energy 
                consumption, shopping, and lifestyle choices, you can gain valuable insights into your environmental impact.
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                <div className="flex flex-col items-center text-center p-4 rounded-xl bg-white/5 border border-white/10">
                  <TrendingUp className="w-8 h-8 text-emerald-400 mb-3" />
                  <h3 className="text-white font-semibold mb-2">Track Emissions</h3>
                  <p className="text-gray-400 text-sm">Monitor your carbon output across all categories</p>
                </div>
                <div className="flex flex-col items-center text-center p-4 rounded-xl bg-white/5 border border-white/10">
                  <BarChart3 className="w-8 h-8 text-teal-400 mb-3" />
                  <h3 className="text-white font-semibold mb-2">Visualize Data</h3>
                  <p className="text-gray-400 text-sm">See detailed breakdowns and trends</p>
                </div>
                <div className="flex flex-col items-center text-center p-4 rounded-xl bg-white/5 border border-white/10">
                  <Activity className="w-8 h-8 text-cyan-400 mb-3" />
                  <h3 className="text-white font-semibold mb-2">Take Action</h3>
                  <p className="text-gray-400 text-sm">Get personalized recommendations to reduce impact</p>
                </div>
              </div>

              <p className="text-gray-300 leading-relaxed text-base mb-6">
                Our platform uses verified emission factors from leading environmental organizations including the EPA, IPCC, 
                and UN Environment Programme to provide accurate calculations. Start tracking today and join thousands of 
                users making a positive impact on the environment.
              </p> 
              <p>     </p>

              <Link to="/">
                <motion.button
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  className="w-full px-8 py-4 rounded-full bg-gradient-to-r from-indigo-500 to-purple-600 text-white font-semibold text-lg shadow-lg shadow-indigo-500/50 hover:shadow-xl hover:shadow-indigo-500/60 transition-all duration-300 flex items-center justify-center gap-2"
                >
                  Track your Carbon footprint
                  <ArrowRight className="w-5 h-5" />
                </motion.button>
              </Link>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

