import { useState } from "react";
import { motion } from "framer-motion";
import { useInView } from "framer-motion";
import { useRef } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Calendar, Clock, ArrowRight, User, Search } from "lucide-react";

export default function Blog() {
  const [selectedCategory, setSelectedCategory] = useState<string>("All");
  const [searchQuery, setSearchQuery] = useState<string>("");

  const heroRef = useRef(null);
  const heroInView = useInView(heroRef, { once: true, margin: "-100px" });

  const blogPosts = [
    {
      id: 1,
      title: "Understanding Your Carbon Footprint: A Beginner's Guide",
      excerpt: "Learn the basics of carbon footprints and why tracking them is crucial for environmental sustainability.",
      content: "Your carbon footprint is the total amount of greenhouse gases, including carbon dioxide and methane, that are generated by your actions.",
      author: "Sarah Johnson",
      date: "2024-01-15",
      readTime: "5 min read",
      category: "Education",
      image: "/assets/images/nature-hero.svg",
      featured: true,
    },
    {
      id: 2,
      title: "10 Simple Ways to Reduce Your Carbon Footprint Today",
      excerpt: "Practical tips and strategies you can implement immediately to lower your environmental impact.",
      content: "Reducing your carbon footprint doesn't have to be complicated. Here are 10 simple changes you can make today.",
      author: "Michael Chen",
      date: "2024-01-12",
      readTime: "8 min read",
      category: "Tips",
      image: "/assets/images/nature-pattern.svg",
      featured: false,
    },
    {
      id: 3,
      title: "The Impact of Transportation on Carbon Emissions",
      excerpt: "Explore how different modes of transportation affect your carbon footprint and discover eco-friendly alternatives.",
      content: "Transportation accounts for approximately 29% of global greenhouse gas emissions.",
      author: "Emily Rodriguez",
      date: "2024-01-10",
      readTime: "6 min read",
      category: "Transport",
      image: "/assets/images/nature-background.svg",
      featured: false,
    },
    {
      id: 4,
      title: "Sustainable Diet: How Your Food Choices Matter",
      excerpt: "Discover the connection between your diet and carbon emissions, and learn how to make more sustainable food choices.",
      content: "Food production accounts for 26% of global greenhouse gas emissions.",
      author: "David Kim",
      date: "2024-01-08",
      readTime: "7 min read",
      category: "Diet",
      image: "/assets/images/leaf-icon.svg",
      featured: false,
    },
    {
      id: 5,
      title: "The Power of Tree Planting in Climate Action",
      excerpt: "Learn how planting trees is one of the most effective ways to combat climate change.",
      content: "Trees are nature's carbon capture technology. A single mature tree can absorb 21.77 kg of CO2 per year.",
      author: "Lisa Anderson",
      date: "2024-01-05",
      readTime: "5 min read",
      category: "Innovation",
      image: "/assets/images/tree-icon.svg",
      featured: false,
    },
    {
      id: 6,
      title: "Renewable Energy: A Path to Carbon Neutrality",
      excerpt: "Understanding renewable energy sources and how they can help reduce your carbon footprint at home.",
      content: "Renewable energy sources like solar and wind power produce zero carbon emissions during operation.",
      author: "James Wilson",
      date: "2024-01-03",
      readTime: "9 min read",
      category: "Energy",
      image: "/assets/images/calculator-icon.svg",
      featured: false,
    },
    {
      id: 7,
      title: "How Trees Combat Climate Change: The Science",
      excerpt: "Deep dive into the scientific mechanisms of how trees absorb and store carbon dioxide.",
      content: "Trees combat climate change through photosynthesis, where they absorb CO2 from the atmosphere.",
      author: "Dr. Maria Garcia",
      date: "2024-01-20",
      readTime: "10 min read",
      category: "Education",
      image: "/assets/images/tree-icon.svg",
      featured: false,
    },
    {
      id: 8,
      title: "Energy Efficiency at Home: Simple Steps",
      excerpt: "Learn how to reduce your home's energy consumption and carbon footprint with simple efficiency improvements.",
      content: "Home energy efficiency can reduce your carbon footprint by up to 30%.",
      author: "Robert Thompson",
      date: "2024-01-18",
      readTime: "6 min read",
      category: "Energy",
      image: "/assets/images/nature-pattern.svg",
      featured: false,
    },
  ];

  const categories = ["All", "Education", "Tips", "Transport", "Diet", "Energy", "Innovation"];

  const filteredPosts = blogPosts.filter(post => {
    const matchesCategory = selectedCategory === "All" || post.category === selectedCategory;
    const matchesSearch = searchQuery === "" || 
      post.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      post.excerpt.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const featuredPost = filteredPosts.find(post => post.featured);
  const regularPosts = filteredPosts.filter(post => !post.featured);

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#0a0a0a] via-[#111111] to-[#1a1a1a]">
      <Navbar />

      {/* Hero Section */}
      <section 
        ref={heroRef}
        className="relative py-32 bg-gradient-to-b from-[#0a0a0a] via-[#111111] to-[#1a1a1a] overflow-hidden"
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={heroInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
            transition={{ duration: 0.8 }}
            className="text-5xl sm:text-6xl md:text-7xl font-bold text-white mb-6 tracking-tight"
          >
            Blog & Insights
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 30 }}
            animate={heroInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="text-lg sm:text-xl md:text-2xl text-gray-300 max-w-3xl mx-auto leading-relaxed"
          >
            Stay informed with the latest articles, tips, and insights on 
            carbon footprint reduction and sustainable living.
          </motion.p>
        </div>
      </section>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24 space-y-12 sm:space-y-16 flex-1">
        {/* Search and Categories */}
        <div className="space-y-6">
          {/* Search Bar */}
          <div className="relative">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
            <Input
              type="text"
              placeholder="Search articles..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-12 py-6 bg-white/5 border-white/10 text-white placeholder-gray-500 rounded-full focus:border-emerald-400/50 focus:ring-emerald-400/50"
            />
          </div>

          {/* Categories */}
          <div className="flex flex-wrap gap-2 sm:gap-3">
            {categories.map((category) => (
              <Button
                key={category}
                onClick={() => setSelectedCategory(category)}
                variant={selectedCategory === category ? "default" : "outline"}
                className={`rounded-full px-6 py-2 transition-all duration-200 ${
                  selectedCategory === category
                    ? "bg-gradient-to-r from-indigo-500 to-purple-600 text-white hover:from-indigo-600 hover:to-purple-700"
                    : "border-white/20 hover:bg-white/5 text-gray-300"
                }`}
              >
                {category}
              </Button>
            ))}
          </div>
        </div>

        {/* Featured Post */}
        {featuredPost && (
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="glass-card rounded-2xl overflow-hidden border border-white/10 hover:border-white/20 transition-all duration-300"
          >
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-0">
              <div className="relative h-48 sm:h-64 lg:h-auto">
                <div 
                  className="absolute inset-0 bg-gradient-to-br from-gray-900 to-gray-800"
                  style={{
                    backgroundImage: `url(${featuredPost.image})`,
                    backgroundSize: "cover",
                    backgroundPosition: "center"
                  }}
                />
                <Badge className="absolute top-4 left-4 bg-white/10 backdrop-blur-lg border border-white/20 text-white">Featured</Badge>
              </div>
              <div className="p-6 sm:p-8 lg:p-12 flex flex-col justify-center bg-white/5 backdrop-blur-lg">
                <Badge className="w-fit mb-4 bg-white/10 backdrop-blur-lg border border-white/20 text-emerald-400">{featuredPost.category}</Badge>
                <h2 className="text-2xl sm:text-3xl font-bold text-white mb-4 tracking-tight">{featuredPost.title}</h2>
                <p className="text-gray-300 mb-6 leading-relaxed text-base">{featuredPost.excerpt}</p>
                <div className="flex flex-wrap items-center gap-3 sm:gap-4 text-xs sm:text-sm text-gray-400 mb-6">
                  <div className="flex items-center gap-2">
                    <User className="w-4 h-4" />
                    <span>{featuredPost.author}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    <span>{new Date(featuredPost.date).toLocaleDateString()}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="w-4 h-4" />
                    <span>{featuredPost.readTime}</span>
                  </div>
                </div>
                <Link to={`/blog/${featuredPost.id}`}>
                  <Button className="w-fit bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white rounded-full px-6 py-3 font-semibold shadow-lg hover:shadow-xl transition-all duration-300">
                    Read More <ArrowRight className="w-4 h-4 ml-2" />
                  </Button>
                </Link>
              </div>
            </div>
          </motion.div>
        )}

        {/* Blog Posts Grid */}
        {regularPosts.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
            {regularPosts.map((post, index) => (
              <motion.div
                key={post.id}
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                whileHover={{ scale: 1.05, y: -8 }}
                className="glass-card rounded-2xl border border-white/10 hover:border-white/20 transition-all duration-300 cursor-pointer overflow-hidden"
              >
                <div className="relative h-40 sm:h-48 overflow-hidden rounded-t-2xl">
                  <div 
                    className="absolute inset-0 bg-gradient-to-br from-gray-900 to-gray-800"
                    style={{
                      backgroundImage: `url(${post.image})`,
                      backgroundSize: "cover",
                      backgroundPosition: "center"
                    }}
                  />
                  <Badge className="absolute top-3 left-3 bg-white/10 backdrop-blur-lg border border-white/20 text-white">{post.category}</Badge>
                </div>
                <div className="p-6 bg-white/5 backdrop-blur-lg">
                  <h3 className="text-xl font-bold text-white mb-3 line-clamp-2 tracking-tight">{post.title}</h3>
                  <p className="text-gray-300 text-sm mb-4 line-clamp-3 leading-relaxed">{post.excerpt}</p>
                  <div className="flex items-center gap-4 text-xs text-gray-400 mb-4 pb-4 border-b border-white/10">
                    <div className="flex items-center gap-1">
                      <User className="w-3 h-3" />
                      <span>{post.author}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      <span>{new Date(post.date).toLocaleDateString()}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      <span>{post.readTime}</span>
                    </div>
                  </div>
                  <Link to={`/blog/${post.id}`}>
                    <Button className="w-full bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white rounded-full px-4 py-2 text-sm font-semibold shadow-lg hover:shadow-xl transition-all duration-300 flex items-center justify-center gap-2">
                      Read More <ArrowRight className="w-4 h-4" />
                    </Button>
                  </Link>
                </div>
              </motion.div>
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <p className="text-gray-400 text-lg">No articles found matching your criteria.</p>
          </div>
        )}

        {/* Newsletter Signup */}
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="glass-card rounded-2xl p-8 sm:p-12 border border-white/10 text-center"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4 tracking-tight">Subscribe to Our Newsletter</h2>
          <p className="text-gray-300 mb-8 sm:mb-8 max-w-2xl mx-auto text-base sm:text-lg leading-relaxed">
            Get the latest articles, tips, and updates delivered straight to your inbox.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 max-w-md mx-auto">
            <Input
              type="email"
              placeholder="Enter your email"
              className="bg-white/5 border-white/10 text-white placeholder-gray-500 rounded-full py-6 focus:border-emerald-400/50 focus:ring-emerald-400/50"
            />
            <Button className="bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white px-6 sm:px-8 whitespace-nowrap rounded-full py-6">
              Subscribe
            </Button>
          </div>
        </motion.div>
      </main>
      <Footer />
    </div>
  );
}
