import { useParams, Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Calendar, Clock, User, ArrowLeft, ArrowRight } from "lucide-react";
import { useScrollAnimation } from "@/hooks/useScrollAnimation";

// All blog posts data
const blogPosts = [
  {
    id: 1,
    title: "Understanding Your Carbon Footprint: A Beginner's Guide",
    excerpt: "Learn the basics of carbon footprints and why tracking them is crucial for environmental sustainability.",
    content: `
      <h2>What is a Carbon Footprint?</h2>
      <p>Your carbon footprint is the total amount of greenhouse gases, including carbon dioxide (CO2) and methane (CH4), that are generated by your actions. This includes everything from driving a car to eating a meal, using electricity, and even buying products.</p>
      
      <h2>Why Does It Matter?</h2>
      <p>Climate change is one of the most pressing challenges of our time. The Earth's average temperature has increased by about 1.1°C since pre-industrial times, primarily due to human activities that release greenhouse gases into the atmosphere.</p>
      
      <p>Understanding your carbon footprint is the first step toward reducing your environmental impact. By tracking your emissions, you can identify areas where you can make changes and see the positive impact of your actions.</p>
      
      <h2>What Contributes to Your Carbon Footprint?</h2>
      <p>Your carbon footprint comes from several key areas:</p>
      <ul>
        <li><strong>Transportation:</strong> Cars, planes, buses, and trains emit CO2 when burning fossil fuels. The average car emits about 0.171 kg CO2 per kilometer.</li>
        <li><strong>Diet:</strong> Food production accounts for 26% of global greenhouse gas emissions. Beef production emits 60 kg CO2 per kg of meat, while vegetables emit only 0.4 kg CO2 per kg.</li>
        <li><strong>Energy:</strong> Electricity and heating from fossil fuels contribute significantly. The average electricity grid emits 0.493 kg CO2 per kWh.</li>
        <li><strong>Shopping:</strong> Manufacturing and transporting products create emissions. A smartphone can emit 78 kg CO2 during production.</li>
        <li><strong>Lifestyle:</strong> Activities like streaming, internet usage, hotel stays, and waste disposal all contribute to your footprint.</li>
      </ul>
      
      <h2>How to Calculate Your Carbon Footprint</h2>
      <p>Calculating your carbon footprint involves tracking your activities in each category and multiplying them by emission factors. Our carbon calculator uses verified data from EPA, IPCC, and UN Environment Programme to provide accurate estimates.</p>
      
      <h2>Getting Started</h2>
      <p>Start by tracking one category at a time. Most people find it easiest to begin with transportation, as it's often the largest contributor. Then move on to diet, energy, and other categories.</p>
      
      <p>Remember, the goal isn't perfection—it's progress. Every small change you make adds up to significant impact over time.</p>
    `,
    author: "Sarah Johnson",
    date: "2024-01-15",
    readTime: "5 min read",
    category: "Education",
    image: "/assets/images/nature-hero.svg",
    featured: true,
  },
  {
    id: 2,
    title: "10 Simple Ways to Reduce Your Carbon Footprint Today",
    excerpt: "Practical tips and strategies you can implement immediately to lower your environmental impact.",
    content: `
      <h2>1. Use Public Transportation or Bike</h2>
      <p>Switching from driving to public transportation can reduce your transport emissions by up to 45%. If you can, bike or walk for short trips—it's completely emission-free!</p>
      
      <h2>2. Reduce Meat Consumption</h2>
      <p>Meat production is one of the largest sources of greenhouse gas emissions. Reducing your meat consumption, especially beef, can significantly lower your carbon footprint. Try having one meat-free day per week to start.</p>
      
      <h2>3. Use Energy-Efficient Appliances</h2>
      <p>LED bulbs use 80% less energy than traditional bulbs. Energy-efficient appliances can reduce your electricity consumption and carbon footprint by up to 30%.</p>
      
      <h2>4. Plant Trees</h2>
      <p>Trees are nature's carbon capture technology. A single tree can absorb 21.77 kg of CO2 per year. Planting trees is one of the most effective ways to combat climate change.</p>
      
      <h2>5. Reduce, Reuse, Recycle</h2>
      <p>Waste production contributes to emissions. By reducing consumption, reusing items, and recycling properly, you can minimize waste and its environmental impact.</p>
      
      <h2>6. Choose Renewable Energy</h2>
      <p>If possible, switch to renewable energy sources like solar or wind power. This can reduce your household carbon footprint by up to 90%.</p>
      
      <h2>7. Reduce Water Usage</h2>
      <p>Water treatment and heating consume energy. Taking shorter showers, fixing leaks, and using water-efficient appliances can reduce both water and energy consumption.</p>
      
      <h2>8. Buy Local Produce</h2>
      <p>Transporting food long distances creates emissions. Buying local, seasonal produce reduces transportation emissions and supports local farmers.</p>
      
      <h2>9. Use LED Bulbs</h2>
      <p>LED bulbs last longer and use significantly less energy than traditional bulbs, reducing both your electricity bill and carbon footprint.</p>
      
      <h2>10. Offset Your Carbon Emissions</h2>
      <p>For emissions you can't avoid, consider offsetting through verified carbon offset programs or by planting trees. Every action counts!</p>
    `,
    author: "Michael Chen",
    date: "2024-01-12",
    readTime: "8 min read",
    category: "Tips",
    image: "/assets/images/nature-pattern.svg",
    featured: false,
  },
  {
    id: 3,
    title: "The Impact of Transportation on Carbon Emissions",
    excerpt: "Explore how different modes of transportation affect your carbon footprint and discover eco-friendly alternatives.",
    content: `
      <h2>Transportation and Climate Change</h2>
      <p>Transportation accounts for approximately 29% of global greenhouse gas emissions, making it one of the largest contributors to climate change. Understanding how different modes of transportation impact the environment is crucial for making informed choices.</p>
      
      <h2>Carbon Emissions by Transportation Mode</h2>
      <p>Different modes of transportation have vastly different carbon footprints:</p>
      <ul>
        <li><strong>Cars:</strong> Average car emits 0.171 kg CO2 per kilometer. Small cars emit less (0.120 kg/km), while large SUVs emit more (0.250 kg/km).</li>
        <li><strong>Trains:</strong> Electric trains are one of the most efficient modes, emitting only 0.041 kg CO2 per kilometer.</li>
        <li><strong>Buses:</strong> Local buses emit 0.089 kg CO2 per kilometer, and emissions are shared among all passengers.</li>
        <li><strong>Planes:</strong> Domestic flights emit 0.255 kg CO2 per kilometer, making them one of the most carbon-intensive modes of travel.</li>
        <li><strong>Electric Vehicles:</strong> EVs emit only 0.051 kg CO2 per kilometer when charged from the average grid, and even less when powered by renewable energy.</li>
        <li><strong>Bicycles and Walking:</strong> These modes produce zero emissions and are the most environmentally friendly options.</li>
      </ul>
      
      <h2>Making Sustainable Transportation Choices</h2>
      <p>Here are some ways to reduce your transportation carbon footprint:</p>
      <ul>
        <li>Walk or bike for short trips whenever possible</li>
        <li>Use public transportation for longer journeys</li>
        <li>Carpool to share emissions with others</li>
        <li>Consider electric or hybrid vehicles</li>
        <li>Combine errands to reduce total distance traveled</li>
        <li>Choose trains over planes for regional travel</li>
      </ul>
      
      <h2>The Future of Transportation</h2>
      <p>As we transition to renewable energy, electric vehicles will become even more environmentally friendly. Public transportation systems are also improving, with many cities investing in electric buses and trains.</p>
    `,
    author: "Emily Rodriguez",
    date: "2024-01-10",
    readTime: "6 min read",
    category: "Transport",
    image: "/assets/images/nature-background.svg",
    featured: false,
  },
  {
    id: 4,
    title: "Sustainable Diet: How Your Food Choices Matter",
    excerpt: "Discover the connection between your diet and carbon emissions, and learn how to make more sustainable food choices.",
    content: `
      <h2>The Carbon Cost of Food</h2>
      <p>Food production accounts for 26% of global greenhouse gas emissions. Every food item you consume has a carbon footprint based on how it's grown, processed, and transported.</p>
      
      <h2>Carbon Footprint of Different Foods</h2>
      <p>Foods have vastly different carbon footprints:</p>
      <ul>
        <li><strong>Beef:</strong> 60 kg CO2 per kg - One of the highest carbon footprints due to methane emissions from cattle and land use for feed.</li>
        <li><strong>Lamb:</strong> 24 kg CO2 per kg - Also high due to methane emissions.</li>
        <li><strong>Cheese:</strong> 21 kg CO2 per kg - Dairy production requires significant resources.</li>
        <li><strong>Pork:</strong> 7 kg CO2 per kg - Lower than beef but still significant.</li>
        <li><strong>Chicken:</strong> 6 kg CO2 per kg - More efficient than red meat.</li>
        <li><strong>Fish:</strong> 5 kg CO2 per kg - Generally lower than meat, but varies by species.</li>
        <li><strong>Eggs:</strong> 4.2 kg CO2 per kg - A good protein source with moderate footprint.</li>
        <li><strong>Rice:</strong> 4 kg CO2 per kg - Staple grain with moderate emissions.</li>
        <li><strong>Beans and Lentils:</strong> 0.9-2 kg CO2 per kg - Excellent protein sources with low footprint.</li>
        <li><strong>Vegetables and Fruits:</strong> 0.4 kg CO2 per kg - Lowest carbon footprint foods.</li>
      </ul>
      
      <h2>Tips for a Sustainable Diet</h2>
      <p>Here are practical ways to reduce your dietary carbon footprint:</p>
      <ul>
        <li>Reduce meat consumption, especially beef and lamb</li>
        <li>Choose plant-based proteins like beans, lentils, and tofu</li>
        <li>Buy local, seasonal produce to reduce transportation emissions</li>
        <li>Reduce food waste—about one-third of food produced is wasted</li>
        <li>Choose organic when possible to support sustainable farming</li>
        <li>Eat more whole foods and fewer processed foods</li>
      </ul>
      
      <h2>The Plant-Based Advantage</h2>
      <p>Plant-based diets have significantly lower carbon footprints than meat-based diets. A vegetarian diet can reduce your food-related emissions by up to 50%, while a vegan diet can reduce them by up to 70%.</p>
    `,
    author: "David Kim",
    date: "2024-01-08",
    readTime: "7 min read",
    category: "Diet",
    image: "/assets/images/leaf-icon.svg",
    featured: false,
  },
  {
    id: 5,
    title: "The Power of Tree Planting in Climate Action",
    excerpt: "Learn how planting trees is one of the most effective ways to combat climate change.",
    content: `
      <h2>Trees: Nature's Carbon Capture Technology</h2>
      <p>Trees are one of the most effective tools we have for fighting climate change. Through photosynthesis, trees absorb carbon dioxide from the atmosphere and store it in their biomass—trunks, branches, leaves, and roots.</p>
      
      <h2>How Much Carbon Do Trees Absorb?</h2>
      <p>The amount of carbon a tree absorbs depends on its species, age, and location:</p>
      <ul>
        <li>A mature tree can absorb 21.77 kg of CO2 per year on average (EPA data)</li>
        <li>Over a 40-year lifetime, a single tree can sequester 1 tonne of CO2 (Arbor Day Foundation)</li>
        <li>Fast-growing trees like bamboo can absorb up to 35 kg CO2 per year</li>
        <li>Long-lived trees like banyan trees can store carbon for centuries</li>
      </ul>
      
      <h2>Global Forest Impact</h2>
      <p>Forests worldwide play a crucial role in climate regulation:</p>
      <ul>
        <li>Global forests absorb 2.6 billion tonnes of CO2 annually (UN Environment Programme)</li>
        <li>1 trillion trees could potentially absorb 200 gigatonnes of CO2 (World Economic Forum)</li>
        <li>Forest restoration can provide 30% of climate mitigation needed by 2030 (Nature.org)</li>
      </ul>
      
      <h2>Best Trees for Carbon Sequestration</h2>
      <p>In Bangladesh and Asia, some of the most effective trees for carbon absorption include:</p>
      <ul>
        <li><strong>Bamboo:</strong> Fast-growing, absorbs 35 kg CO2 per year</li>
        <li><strong>Banyan Tree:</strong> Massive carbon storage, up to 30 kg CO2 per year</li>
        <li><strong>Teak:</strong> Long-lived hardwood, 28 kg CO2 per year</li>
        <li><strong>Mahogany:</strong> Premium hardwood, 26.5 kg CO2 per year</li>
        <li><strong>Jackfruit:</strong> National fruit of Bangladesh, 25 kg CO2 per year</li>
        <li><strong>Neem:</strong> Native to Bangladesh, 22 kg CO2 per year</li>
      </ul>
      
      <h2>How to Plant Trees Effectively</h2>
      <p>To maximize carbon sequestration, consider:</p>
      <ul>
        <li>Choosing native species adapted to local conditions</li>
        <li>Planting a mix of fast-growing and long-lived species</li>
        <li>Ensuring proper spacing and care for healthy growth</li>
        <li>Supporting reforestation programs in your area</li>
      </ul>
    `,
    author: "Lisa Anderson",
    date: "2024-01-05",
    readTime: "5 min read",
    category: "Innovation",
    image: "/assets/images/tree-icon.svg",
    featured: false,
  },
  {
    id: 6,
    title: "Renewable Energy: A Path to Carbon Neutrality",
    excerpt: "Understanding renewable energy sources and how they can help reduce your carbon footprint at home.",
    content: `
      <h2>What is Renewable Energy?</h2>
      <p>Renewable energy comes from natural sources that are constantly replenished, such as sunlight, wind, water, and geothermal heat. Unlike fossil fuels, renewable energy sources produce little to no greenhouse gas emissions during operation.</p>
      
      <h2>Types of Renewable Energy</h2>
      <ul>
        <li><strong>Solar Power:</strong> Converts sunlight into electricity using photovoltaic panels. Can be installed on rooftops or in large solar farms.</li>
        <li><strong>Wind Power:</strong> Uses wind turbines to generate electricity. Highly effective in windy areas.</li>
        <li><strong>Hydropower:</strong> Generates electricity from flowing water. Most common in regions with rivers and dams.</li>
        <li><strong>Geothermal:</strong> Uses heat from the Earth's interior to generate electricity and heat buildings.</li>
        <li><strong>Biomass:</strong> Converts organic materials into energy, though can have higher emissions than other renewables.</li>
      </ul>
      
      <h2>Carbon Footprint Comparison</h2>
      <p>Renewable energy sources have dramatically lower carbon footprints than fossil fuels:</p>
      <ul>
        <li>Coal: 3.12 kg CO2 per kWh</li>
        <li>Natural Gas: 2.07 kg CO2 per m³</li>
        <li>Solar Power: 0.04-0.05 kg CO2 per kWh (during manufacturing)</li>
        <li>Wind Power: 0.02-0.03 kg CO2 per kWh (during manufacturing)</li>
        <li>Hydropower: 0.01-0.02 kg CO2 per kWh</li>
      </ul>
      
      <h2>Switching to Renewable Energy</h2>
      <p>Switching to renewable energy can reduce your household carbon footprint by up to 90%. Here's how to get started:</p>
      <ul>
        <li>Install solar panels on your roof</li>
        <li>Choose a renewable energy provider if available</li>
        <li>Use solar water heaters</li>
        <li>Invest in community solar projects</li>
        <li>Support renewable energy policies</li>
      </ul>
      
      <h2>The Future of Energy</h2>
      <p>As renewable energy technology improves and costs decrease, it's becoming increasingly accessible. Many countries are setting ambitious goals to transition to 100% renewable energy by 2050.</p>
    `,
    author: "James Wilson",
    date: "2024-01-03",
    readTime: "9 min read",
    category: "Energy",
    image: "/assets/images/calculator-icon.svg",
    featured: false,
  },
  {
    id: 7,
    title: "How Trees Combat Climate Change: The Science",
    excerpt: "Deep dive into the scientific mechanisms of how trees absorb and store carbon dioxide.",
    content: `
      <h2>The Science of Photosynthesis</h2>
      <p>Trees combat climate change through photosynthesis, a process where they absorb carbon dioxide (CO2) from the atmosphere and convert it into oxygen and glucose. The carbon is stored in the tree's biomass—trunk, branches, leaves, and roots.</p>
      
      <h2>How Carbon Sequestration Works</h2>
      <p>During photosynthesis, trees:</p>
      <ol>
        <li>Absorb CO2 from the atmosphere through their leaves</li>
        <li>Combine it with water and sunlight to create glucose (sugar)</li>
        <li>Release oxygen as a byproduct</li>
        <li>Store carbon in their biomass</li>
      </ol>
      
      <p>This process continues throughout the tree's lifetime, with larger, older trees storing more carbon.</p>
      
      <h2>Carbon Storage in Different Tree Parts</h2>
      <p>Carbon is stored throughout the tree:</p>
      <ul>
        <li><strong>Trunk:</strong> The largest carbon reservoir, storing carbon for decades or centuries</li>
        <li><strong>Branches:</strong> Secondary storage, pruned branches can be used for bioenergy</li>
        <li><strong>Leaves:</strong> Temporary storage, returns to atmosphere when leaves fall</li>
        <li><strong>Roots:</strong> Long-term storage, carbon remains in soil even after tree dies</li>
      </ul>
      
      <h2>Forests as Carbon Sinks</h2>
      <p>Forests act as carbon sinks, absorbing more CO2 than they release. The UN estimates that forests can provide 30% of the climate mitigation needed by 2030. Global forests currently absorb 2.6 billion tonnes of CO2 annually.</p>
      
      <h2>Factors Affecting Carbon Absorption</h2>
      <p>Several factors influence how much carbon a tree can absorb:</p>
      <ul>
        <li><strong>Species:</strong> Fast-growing species absorb more carbon quickly</li>
        <li><strong>Age:</strong> Mature trees absorb more carbon than young trees</li>
        <li><strong>Location:</strong> Trees in tropical regions typically grow faster</li>
        <li><strong>Health:</strong> Healthy trees absorb more carbon than stressed trees</li>
        <li><strong>Density:</strong> Dense forests store more carbon per hectare</li>
      </ul>
    `,
    author: "Dr. Maria Garcia",
    date: "2024-01-20",
    readTime: "10 min read",
    category: "Education",
    image: "/assets/images/tree-icon.svg",
    featured: false,
  },
  {
    id: 8,
    title: "Energy Efficiency at Home: Simple Steps",
    excerpt: "Learn how to reduce your home's energy consumption and carbon footprint with simple efficiency improvements.",
    content: `
      <h2>Why Energy Efficiency Matters</h2>
      <p>Home energy efficiency can reduce your carbon footprint by up to 30%. It also saves money on utility bills and improves comfort. The average home emits about 4-5 tonnes of CO2 per year from energy use alone.</p>
      
      <h2>Simple Energy Efficiency Steps</h2>
      <ul>
        <li><strong>Switch to LED Bulbs:</strong> Use 80% less energy than traditional bulbs and last 25 times longer</li>
        <li><strong>Insulate Your Home:</strong> Proper insulation can reduce heating and cooling costs by 30%</li>
        <li><strong>Use Programmable Thermostats:</strong> Save up to 10% on heating and cooling by adjusting temperature when away</li>
        <li><strong>Seal Air Leaks:</strong> Caulk and weatherstrip windows and doors to prevent heat loss</li>
        <li><strong>Upgrade to Energy-Efficient Appliances:</strong> ENERGY STAR appliances use 10-50% less energy</li>
        <li><strong>Use Smart Power Strips:</strong> Eliminate phantom power from electronics</li>
        <li><strong>Install Low-Flow Showerheads:</strong> Reduce water heating costs by 50%</li>
        <li><strong>Maintain Your HVAC System:</strong> Regular maintenance improves efficiency by 20%</li>
      </ul>
      
      <h2>Low-Cost Improvements</h2>
      <p>Many energy efficiency improvements are low-cost or free:</p>
      <ul>
        <li>Unplug electronics when not in use</li>
        <li>Use natural light during the day</li>
        <li>Close curtains at night to retain heat</li>
        <li>Wash clothes in cold water</li>
        <li>Air dry clothes instead of using a dryer</li>
        <li>Cook efficiently with lids on pots</li>
      </ul>
      
      <h2>Long-Term Investments</h2>
      <p>For bigger impact, consider:</p>
      <ul>
        <li>Solar panel installation</li>
        <li>Energy-efficient windows</li>
        <li>Heat pumps for heating and cooling</li>
        <li>Smart home automation systems</li>
      </ul>
    `,
    author: "Robert Thompson",
    date: "2024-01-18",
    readTime: "6 min read",
    category: "Energy",
    image: "/assets/images/nature-pattern.svg",
    featured: false,
  },
];

export default function BlogPost() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const heroAnimation = useScrollAnimation({ threshold: 0.2, triggerOnce: true });

  const post = blogPosts.find(p => p.id === parseInt(id || "0"));
  const currentIndex = blogPosts.findIndex(p => p.id === parseInt(id || "0"));
  const nextPost = currentIndex >= 0 && currentIndex < blogPosts.length - 1 ? blogPosts[currentIndex + 1] : null;
  const prevPost = currentIndex > 0 ? blogPosts[currentIndex - 1] : null;

  if (!post) {
    return (
      <div className="min-h-screen bg-white flex flex-col">
        <Navbar />
        <main className="max-w-4xl mx-auto px-4 sm:px-6 py-16 text-center">
          <h1 className="text-4xl font-semibold text-gray-900 mb-4">Post Not Found</h1>
          <p className="text-gray-600 mb-8">The blog post you're looking for doesn't exist.</p>
          <Link to="/blog">
            <Button className="bg-gray-900 text-white rounded-full px-6 py-2">
              Back to Blog
            </Button>
          </Link>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Navbar />

      {/* Hero Section */}
      <div 
        ref={heroAnimation.elementRef}
        className="relative overflow-hidden bg-gradient-to-br from-gray-50 via-white to-gray-50 text-gray-900"
      >
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
          <Link to="/blog">
            <Button variant="ghost" className="mb-6 text-gray-600 hover:text-gray-900 rounded-full">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Blog
            </Button>
          </Link>
          <div className="flex items-center gap-2 mb-4">
            <span className="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm font-medium">
              {post.category}
            </span>
          </div>
          <h1 
            className={`text-4xl sm:text-5xl lg:text-6xl font-semibold mb-6 tracking-tight text-gray-900 transition-all duration-1000 delay-100 ${
              heroAnimation.isVisible ? "translate-y-0 opacity-100" : "translate-y-4 opacity-90"
            }`}
          >
            {post.title}
          </h1>
          <div className="flex flex-wrap items-center gap-4 text-sm text-gray-600 mb-8">
            <div className="flex items-center gap-2">
              <User className="w-4 h-4" />
              <span>{post.author}</span>
            </div>
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4" />
              <span>{new Date(post.date).toLocaleDateString()}</span>
            </div>
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4" />
              <span>{post.readTime}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-8 sm:py-16 space-y-8">
        {/* Featured Image */}
        <div className="relative h-64 sm:h-96 rounded-2xl overflow-hidden mb-8">
          <div 
            className="absolute inset-0 bg-gradient-to-br from-gray-100 to-gray-50"
            style={{
              backgroundImage: `url(${post.image})`,
              backgroundSize: "cover",
              backgroundPosition: "center"
            }}
          />
        </div>

        {/* Article Content */}
        <Card className="border-gray-200 bg-white rounded-2xl">
          <CardContent className="p-8 sm:p-12">
            <div 
              className="article-content"
              dangerouslySetInnerHTML={{ __html: post.content }}
            />
          </CardContent>
        </Card>

        {/* Navigation */}
        <div className="flex flex-col sm:flex-row gap-4 justify-between pt-8 border-t border-gray-200">
          {prevPost ? (
            <Link to={`/blog/${prevPost.id}`} className="flex-1">
              <Button variant="outline" className="w-full border-gray-300 hover:bg-gray-100 rounded-full">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Previous: {prevPost.title.length > 40 ? prevPost.title.substring(0, 40) + "..." : prevPost.title}
              </Button>
            </Link>
          ) : (
            <div className="flex-1" />
          )}
          {nextPost ? (
            <Link to={`/blog/${nextPost.id}`} className="flex-1">
              <Button variant="outline" className="w-full border-gray-300 hover:bg-gray-100 rounded-full">
                Next: {nextPost.title.length > 40 ? nextPost.title.substring(0, 40) + "..." : nextPost.title}
                <ArrowRight className="w-4 h-4 ml-2" />
              </Button>
            </Link>
          ) : (
            <div className="flex-1" />
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
}

