import { useParams, Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useScrollAnimation } from "@/hooks/useScrollAnimation";
import { ArrowLeft, Calendar, User, ExternalLink, Download, BookOpen, FileText, Video } from "lucide-react";

// All resources data
const resources = [
  {
    id: "understanding-carbon-footprint",
    title: "Understanding Your Carbon Footprint",
    description: "Comprehensive guide explaining what a carbon footprint is, how it's calculated, and why it matters for climate change. Learn about different emission sources and how to measure your impact.",
    category: "Guides",
    icon: BookOpen,
    content: `
      <h2>What is a Carbon Footprint?</h2>
      <p>Your carbon footprint is the total amount of greenhouse gases, including carbon dioxide (CO2) and methane (CH4), that are generated by your actions. This includes everything from driving a car to eating a meal, using electricity, and buying products.</p>
      
      <h2>Why Does It Matter?</h2>
      <p>Climate change is one of the most pressing challenges of our time. The Earth's average temperature has increased by about 1.1°C since pre-industrial times, primarily due to human activities that release greenhouse gases into the atmosphere.</p>
      
      <h2>How to Calculate Your Carbon Footprint</h2>
      <p>Calculating your carbon footprint involves tracking your activities in each category and multiplying them by emission factors. Our carbon calculator uses verified data from EPA, IPCC, and UN Environment Programme to provide accurate estimates.</p>
      
      <h2>Key Categories</h2>
      <ul>
        <li><strong>Transportation:</strong> Cars, planes, buses, and trains emit CO2 when burning fossil fuels.</li>
        <li><strong>Diet:</strong> Food production accounts for 26% of global greenhouse gas emissions.</li>
        <li><strong>Energy:</strong> Electricity and heating from fossil fuels contribute significantly.</li>
        <li><strong>Shopping:</strong> Manufacturing and transporting products create emissions.</li>
        <li><strong>Lifestyle:</strong> Activities like streaming, internet usage, and waste disposal all contribute.</li>
      </ul>
      
      <h2>Getting Started</h2>
      <p>Start by tracking one category at a time. Most people find it easiest to begin with transportation, as it's often the largest contributor. Then move on to diet, energy, and other categories.</p>
    `,
    author: "MyCarbonFootprint Team",
    date: "2024-01-15",
    type: "guide",
    link: "#"
  },
  {
    id: "reduce-emissions",
    title: "How to Reduce Your Emissions",
    description: "Practical, actionable tips for lowering your carbon footprint. From transportation to diet choices, discover proven strategies to reduce your environmental impact.",
    category: "Guides",
    icon: BookOpen,
    content: `
      <h2>Transportation</h2>
      <p>Switching from driving to public transportation can reduce your transport emissions by up to 45%. If you can, bike or walk for short trips—it's completely emission-free!</p>
      
      <h2>Diet</h2>
      <p>Meat production is one of the largest sources of greenhouse gas emissions. Reducing your meat consumption, especially beef, can significantly lower your carbon footprint. Try having one meat-free day per week to start.</p>
      
      <h2>Energy</h2>
      <p>LED bulbs use 80% less energy than traditional bulbs. Energy-efficient appliances can reduce your electricity consumption and carbon footprint by up to 30%.</p>
      
      <h2>Tree Planting</h2>
      <p>Trees are nature's carbon capture technology. A single tree can absorb 21.77 kg of CO2 per year. Planting trees is one of the most effective ways to combat climate change.</p>
      
      <h2>Shopping</h2>
      <p>By reducing consumption, reusing items, and recycling properly, you can minimize waste and its environmental impact.</p>
    `,
    author: "Sarah Johnson",
    date: "2024-01-12",
    type: "guide",
    link: "#"
  },
  {
    id: "transportation-alternatives",
    title: "Transportation Alternatives",
    description: "Explore eco-friendly transportation options and their carbon impact. Compare cars, trains, buses, bikes, and walking to make informed choices.",
    category: "Guides",
    icon: BookOpen,
    content: `
      <h2>Carbon Emissions by Mode</h2>
      <p>Different modes of transportation have vastly different carbon footprints:</p>
      <ul>
        <li><strong>Cars:</strong> Average car emits 0.171 kg CO2 per kilometer</li>
        <li><strong>Trains:</strong> Electric trains emit only 0.041 kg CO2 per kilometer</li>
        <li><strong>Buses:</strong> Local buses emit 0.089 kg CO2 per kilometer</li>
        <li><strong>Planes:</strong> Domestic flights emit 0.255 kg CO2 per kilometer</li>
        <li><strong>Electric Vehicles:</strong> EVs emit only 0.051 kg CO2 per kilometer</li>
        <li><strong>Bicycles and Walking:</strong> Zero emissions</li>
      </ul>
      
      <h2>Making Sustainable Choices</h2>
      <p>Walk or bike for short trips whenever possible. Use public transportation for longer journeys. Consider electric or hybrid vehicles. Choose trains over planes for regional travel.</p>
    `,
    author: "Emily Rodriguez",
    date: "2024-01-10",
    type: "guide",
    link: "#"
  },
  {
    id: "sustainable-diet-guide",
    title: "Sustainable Diet Guide",
    description: "Learn how your food choices impact the environment. Discover the carbon footprint of different foods and how to make more sustainable dietary decisions.",
    category: "Guides",
    icon: BookOpen,
    content: `
      <h2>Carbon Footprint of Different Foods</h2>
      <p>Foods have vastly different carbon footprints:</p>
      <ul>
        <li><strong>Beef:</strong> 60 kg CO2 per kg - One of the highest carbon footprints</li>
        <li><strong>Lamb:</strong> 24 kg CO2 per kg - Also high due to methane emissions</li>
        <li><strong>Cheese:</strong> 21 kg CO2 per kg - Dairy production requires significant resources</li>
        <li><strong>Chicken:</strong> 6 kg CO2 per kg - More efficient than red meat</li>
        <li><strong>Beans and Lentils:</strong> 0.9-2 kg CO2 per kg - Excellent protein sources with low footprint</li>
        <li><strong>Vegetables and Fruits:</strong> 0.4 kg CO2 per kg - Lowest carbon footprint foods</li>
      </ul>
      
      <h2>Tips for a Sustainable Diet</h2>
      <p>Reduce meat consumption, especially beef and lamb. Choose plant-based proteins like beans, lentils, and tofu. Buy local, seasonal produce to reduce transportation emissions. Reduce food waste—about one-third of food produced is wasted.</p>
    `,
    author: "David Kim",
    date: "2024-01-08",
    type: "guide",
    link: "#"
  },
  {
    id: "tree-planting-guide",
    title: "Tree Planting Guide",
    description: "Complete guide to tree planting for carbon offset. Learn which trees are most effective, how to plant them, and calculate your carbon impact.",
    category: "Guides",
    icon: BookOpen,
    content: `
      <h2>Best Trees for Carbon Sequestration in Bangladesh</h2>
      <p>In Bangladesh and Asia, some of the most effective trees for carbon absorption include:</p>
      <ul>
        <li><strong>Bamboo (বাঁশ):</strong> Fast-growing, absorbs 35 kg CO2 per year</li>
        <li><strong>Banyan Tree (বট):</strong> Massive carbon storage, up to 30 kg CO2 per year</li>
        <li><strong>Teak (সেগুন):</strong> Long-lived hardwood, 28 kg CO2 per year</li>
        <li><strong>Mahogany (মেহগনি):</strong> Premium hardwood, 26.5 kg CO2 per year</li>
        <li><strong>Jackfruit (কাঠাল):</strong> National fruit of Bangladesh, 25 kg CO2 per year</li>
        <li><strong>Neem (নিম):</strong> Native to Bangladesh, 22 kg CO2 per year</li>
        <li><strong>Mango (আম):</strong> National tree of Bangladesh, 20.5 kg CO2 per year</li>
      </ul>
      
      <h2>How to Plant Trees Effectively</h2>
      <p>To maximize carbon sequestration, consider choosing native species adapted to local conditions, planting a mix of fast-growing and long-lived species, ensuring proper spacing and care for healthy growth, and supporting reforestation programs in your area.</p>
      
      <h2>Calculating Your Impact</h2>
      <p>Use our tree planting calculator to see how many trees you need to plant to offset your carbon footprint. A single tree can absorb 21.77 kg of CO2 per year on average.</p>
    `,
    author: "Lisa Anderson",
    date: "2024-01-20",
    type: "guide",
    link: "/tree-planting"
  },
  {
    id: "climate-change-report-2024",
    title: "Climate Change Report 2024",
    description: "Latest research on climate change impacts, trends, and projections. Based on IPCC and UN Environment Programme data.",
    category: "Reports",
    icon: FileText,
    content: `
      <h2>Key Findings</h2>
      <p>The latest climate change research shows that global temperatures have increased by 1.1°C since pre-industrial times, primarily due to human activities that release greenhouse gases into the atmosphere.</p>
      
      <h2>Global Emissions</h2>
      <p>Global greenhouse gas emissions continue to rise, with transportation, energy, and agriculture being the largest contributors. The transportation sector accounts for 29% of global emissions, while food production accounts for 26%.</p>
      
      <h2>Projected Impacts</h2>
      <p>If current trends continue, global temperatures could rise by 2-3°C by the end of the century, leading to severe climate impacts including sea-level rise, extreme weather events, and ecosystem disruption.</p>
      
      <h2>Mitigation Strategies</h2>
      <p>To limit warming to 1.5°C, we need to reduce global emissions by 45% by 2030 and reach net-zero by 2050. This requires immediate action across all sectors, including transitioning to renewable energy, reducing deforestation, and changing agricultural practices.</p>
    `,
    author: "UN Environment Programme",
    date: "2024-01-15",
    type: "report",
    link: "#"
  },
  {
    id: "carbon-emission-statistics",
    title: "Carbon Emission Statistics",
    description: "Global and regional emission data from EPA, IEA, and other authoritative sources. Understand current emission levels and trends.",
    category: "Reports",
    icon: FileText,
    content: `
      <h2>Global Emissions</h2>
      <p>Global carbon dioxide emissions reached 36.8 billion tonnes in 2023, with China, the United States, and India being the largest emitters.</p>
      
      <h2>Emission Sources</h2>
      <p>The largest sources of global emissions include:</p>
      <ul>
        <li>Transportation: 29%</li>
        <li>Energy production: 25%</li>
        <li>Food production: 26%</li>
        <li>Industry: 21%</li>
        <li>Buildings: 6%</li>
      </ul>
      
      <h2>Regional Trends</h2>
      <p>While emissions are declining in many developed countries, they continue to rise in developing countries as they industrialize and urbanize. However, per capita emissions remain highest in developed countries.</p>
      
      <h2>Data Sources</h2>
      <p>All data is sourced from EPA, IEA, IPCC, and UN Environment Programme, ensuring accuracy and reliability.</p>
    `,
    author: "EPA & IEA",
    date: "2024-01-12",
    type: "report",
    link: "#"
  },
  {
    id: "forest-carbon-sequestration",
    title: "Forest Carbon Sequestration Study",
    description: "Research on how forests absorb CO2 and their potential for climate mitigation. Based on Arbor Day Foundation and Nature.org data.",
    category: "Reports",
    icon: FileText,
    content: `
      <h2>Forest Carbon Sequestration</h2>
      <p>Forests worldwide play a crucial role in climate regulation. Global forests absorb 2.6 billion tonnes of CO2 annually, making them one of the most important natural carbon sinks.</p>
      
      <h2>Tree Carbon Absorption</h2>
      <p>A single mature tree can absorb 21.77 kg of CO2 per year on average, and over its 40-year lifetime, a tree can sequester 1 tonne of CO2. Different tree species have different absorption rates:</p>
      <ul>
        <li>Fast-growing species like bamboo can absorb up to 35 kg CO2 per year</li>
        <li>Long-lived species like banyan trees can store carbon for centuries</li>
        <li>Hardwood species like teak and mahogany provide long-term carbon storage</li>
      </ul>
      
      <h2>Forest Restoration Potential</h2>
      <p>Forest restoration can provide 30% of the climate mitigation needed by 2030. The World Economic Forum estimates that 1 trillion trees could potentially absorb 200 gigatonnes of CO2.</p>
      
      <h2>Best Practices</h2>
      <p>To maximize carbon sequestration, forests should be managed sustainably, native species should be prioritized, and reforestation programs should be supported.</p>
    `,
    author: "Arbor Day Foundation",
    date: "2024-01-18",
    type: "report",
    link: "#"
  },
  {
    id: "renewable-energy-impact",
    title: "Renewable Energy Impact Report",
    description: "Analysis of renewable energy sources and their carbon reduction potential. Learn about solar, wind, and other clean energy options.",
    category: "Reports",
    icon: FileText,
    content: `
      <h2>Renewable Energy Growth</h2>
      <p>Renewable energy sources are growing rapidly worldwide. Solar and wind power are now among the cheapest sources of electricity in many regions, making them increasingly accessible.</p>
      
      <h2>Carbon Reduction Potential</h2>
      <p>Switching to renewable energy can reduce your household carbon footprint by up to 90%. Solar panels on your roof can generate clean electricity for 25-30 years, significantly reducing your reliance on fossil fuels.</p>
      
      <h2>Energy Sources Comparison</h2>
      <ul>
        <li>Coal: 3.12 kg CO2 per kWh</li>
        <li>Natural Gas: 2.07 kg CO2 per m³</li>
        <li>Solar Power: 0.04-0.05 kg CO2 per kWh (during manufacturing)</li>
        <li>Wind Power: 0.02-0.03 kg CO2 per kWh (during manufacturing)</li>
        <li>Hydropower: 0.01-0.02 kg CO2 per kWh</li>
      </ul>
      
      <h2>Future Outlook</h2>
      <p>As renewable energy technology improves and costs decrease, it's becoming increasingly accessible. Many countries are setting ambitious goals to transition to 100% renewable energy by 2050.</p>
    `,
    author: "IEA",
    date: "2024-01-16",
    type: "report",
    link: "#"
  },
  {
    id: "carbon-tracking-tutorial",
    title: "Introduction to Carbon Tracking",
    description: "Watch our tutorial series on how to track your carbon footprint. Step-by-step guides for using the calculator and understanding your results.",
    category: "Videos",
    icon: Video,
    content: `
      <h2>Getting Started</h2>
      <p>Our carbon tracking tutorial series will guide you through the process of calculating and tracking your carbon footprint. Learn how to use our calculator, understand your results, and make informed decisions to reduce your impact.</p>
      
      <h2>Video Series</h2>
      <ul>
        <li><strong>Episode 1:</strong> Introduction to Carbon Footprints</li>
        <li><strong>Episode 2:</strong> Using the Carbon Calculator</li>
        <li><strong>Episode 3:</strong> Understanding Your Results</li>
        <li><strong>Episode 4:</strong> Reducing Your Transportation Emissions</li>
        <li><strong>Episode 5:</strong> Making Sustainable Food Choices</li>
        <li><strong>Episode 6:</strong> Energy Efficiency at Home</li>
      </ul>
      
      <h2>What You'll Learn</h2>
      <p>By the end of this series, you'll be able to calculate your carbon footprint, understand which activities contribute most to your emissions, and develop a personalized plan to reduce your environmental impact.</p>
    `,
    author: "MyCarbonFootprint Team",
    date: "2024-01-15",
    type: "video",
    link: "#"
  },
  {
    id: "success-stories",
    title: "Success Stories",
    description: "Inspiring stories from users who have successfully reduced their carbon footprint. Learn from real examples of climate action.",
    category: "Videos",
    icon: Video,
    content: `
      <h2>Real User Stories</h2>
      <p>Hear from users who have successfully reduced their carbon footprint and made a positive impact on the environment. These inspiring stories show that every action counts and that small changes can lead to significant results.</p>
      
      <h2>Featured Stories</h2>
      <ul>
        <li><strong>Ahmed's Story:</strong> How switching to public transportation reduced his emissions by 40%</li>
        <li><strong>Fatima's Journey:</strong> Reducing meat consumption and its impact on her carbon footprint</li>
        <li><strong>Rashid's Initiative:</strong> Planting 50 trees in his neighborhood</li>
        <li><strong>Community Project:</strong> A local group's efforts to reduce waste and emissions</li>
      </ul>
      
      <h2>Lessons Learned</h2>
      <p>Each story includes practical tips and lessons learned that you can apply to your own journey toward reducing your carbon footprint.</p>
    `,
    author: "Community",
    date: "2024-01-12",
    type: "video",
    link: "#"
  },
  {
    id: "expert-interviews",
    title: "Expert Interviews",
    description: "Insights from climate scientists, environmental experts, and sustainability leaders. Learn from leading voices in climate action.",
    category: "Videos",
    icon: Video,
    content: `
      <h2>Expert Perspectives</h2>
      <p>Gain insights from leading climate scientists, environmental experts, and sustainability leaders. These interviews provide valuable perspectives on climate change, carbon reduction strategies, and the future of environmental action.</p>
      
      <h2>Featured Experts</h2>
      <ul>
        <li><strong>Dr. Sarah Ahmed:</strong> Climate Scientist - "Understanding Climate Change"</li>
        <li><strong>Prof. Muhammad Rahman:</strong> Environmental Expert - "Carbon Sequestration Strategies"</li>
        <li><strong>Ms. Ayesha Khan:</strong> Sustainability Leader - "Practical Steps for Individuals"</li>
        <li><strong>Dr. Hasan Ali:</strong> Forest Researcher - "Tree Planting and Climate Mitigation"</li>
      </ul>
      
      <h2>Topics Covered</h2>
      <p>These interviews cover a wide range of topics, from the science of climate change to practical strategies for reducing your carbon footprint. Each expert brings unique insights and actionable advice.</p>
    `,
    author: "Various Experts",
    date: "2024-01-10",
    type: "video",
    link: "#"
  },
  {
    id: "tree-planting-tutorial",
    title: "Tree Planting Tutorial",
    description: "Learn how to plant trees effectively for carbon offset. Video guide covering tree selection, planting techniques, and care.",
    category: "Videos",
    icon: Video,
    content: `
      <h2>Tree Planting Guide</h2>
      <p>This comprehensive video tutorial will teach you everything you need to know about planting trees effectively for carbon offset. Learn how to select the right trees, plant them correctly, and care for them to maximize carbon sequestration.</p>
      
      <h2>Video Content</h2>
      <ul>
        <li><strong>Part 1:</strong> Selecting the Right Trees for Your Area</li>
        <li><strong>Part 2:</strong> Preparing the Planting Site</li>
        <li><strong>Part 3:</strong> Planting Techniques</li>
        <li><strong>Part 4:</strong> Caring for Your Trees</li>
        <li><strong>Part 5:</strong> Calculating Your Carbon Impact</li>
      </ul>
      
      <h2>Best Trees for Bangladesh</h2>
      <p>Learn about the best trees for carbon sequestration in Bangladesh, including bamboo, banyan, teak, mahogany, jackfruit, and neem trees. Each species has unique characteristics and carbon absorption rates.</p>
      
      <h2>Practical Tips</h2>
      <p>Get practical tips on spacing, watering, fertilization, and protection from pests and diseases. Learn how to ensure your trees grow healthy and maximize their carbon sequestration potential.</p>
    `,
    author: "Arbor Day Foundation",
    date: "2024-01-20",
    type: "video",
    link: "#"
  },
];

export default function ResourceDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const heroAnimation = useScrollAnimation({ threshold: 0.2, triggerOnce: true });

  const resource = resources.find(r => r.id === id);

  if (!resource) {
    return (
      <div className="min-h-screen bg-white flex flex-col">
        <Navbar />
        <main className="max-w-4xl mx-auto px-4 sm:px-6 py-16 text-center">
          <h1 className="text-4xl font-semibold text-gray-900 mb-4">Resource Not Found</h1>
          <p className="text-gray-600 mb-8">The resource you're looking for doesn't exist.</p>
          <Link to="/resources">
            <Button className="bg-gray-900 text-white rounded-full px-6 py-2">
              Back to Resources
            </Button>
          </Link>
        </main>
        <Footer />
      </div>
    );
  }

  const IconComponent = resource.icon;

  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Navbar />

      {/* Hero Section */}
      <div 
        ref={heroAnimation.elementRef}
        className="relative overflow-hidden bg-gradient-to-br from-gray-50 via-white to-gray-50 text-gray-900"
      >
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
          <Link to="/resources">
            <Button variant="ghost" className="mb-6 text-gray-600 hover:text-gray-900 rounded-full">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Resources
            </Button>
          </Link>
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-2xl bg-gray-100 flex items-center justify-center">
              <IconComponent className="w-6 h-6 text-gray-900" />
            </div>
            <span className="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm font-medium">
              {resource.category}
            </span>
          </div>
          <h1 
            className={`text-4xl sm:text-5xl lg:text-6xl font-semibold mb-6 tracking-tight text-gray-900 transition-all duration-1000 delay-100 ${
              heroAnimation.isVisible ? "translate-y-0 opacity-100" : "translate-y-4 opacity-90"
            }`}
          >
            {resource.title}
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 mb-8 leading-relaxed">
            {resource.description}
          </p>
          <div className="flex flex-wrap items-center gap-4 text-sm text-gray-600">
            <div className="flex items-center gap-2">
              <User className="w-4 h-4" />
              <span>{resource.author}</span>
            </div>
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4" />
              <span>{new Date(resource.date).toLocaleDateString()}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-8 sm:py-16 space-y-8">
        {/* Resource Content */}
        <Card className="border-gray-200 bg-white rounded-2xl">
          <CardContent className="p-8 sm:p-12">
            <div 
              className="article-content"
              dangerouslySetInnerHTML={{ __html: resource.content }}
            />
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center pt-8 border-t border-gray-200">
          {resource.link && resource.link !== "#" ? (
            <Link to={resource.link}>
              <Button className="bg-gray-900 hover:bg-gray-800 text-white rounded-full px-6 py-2">
                {resource.type === "guide" && <BookOpen className="w-4 h-4 mr-2" />}
                {resource.type === "report" && <FileText className="w-4 h-4 mr-2" />}
                {resource.type === "video" && <Video className="w-4 h-4 mr-2" />}
                {resource.type === "guide" ? "View Guide" : resource.type === "report" ? "View Report" : "Watch Video"}
              </Button>
            </Link>
          ) : (
            <Button variant="outline" className="border-gray-300 hover:bg-gray-100 rounded-full px-6 py-2">
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </Button>
          )}
          <Link to="/resources">
            <Button variant="outline" className="border-gray-300 hover:bg-gray-100 rounded-full px-6 py-2">
              Explore More Resources
            </Button>
          </Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}

